name: xogame
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  dotted_line: ^3.1.0
  just_audio: ^0.9.22
  audioplayers: ^6.1.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/imgs/
    - assets/sounds/background_music.mp3
  fonts:
    - family: CooperBlack
      fonts:
        - asset: assets/fonts/CooperBlack.ttf
    - family: KleeOne
      fonts:
        - asset: assets/fonts/KleeOne.ttf
